#!/usr/bin/env python3
# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Install the stable user-local Hardened Chromium service command.

This development-tree installer deliberately installs a tiny Python wrapper,
not Chromium itself. The wrapper forwards to the verified source/build tree so
local applications can use one stable PATH command.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import sys
from typing import Any


COMMAND_NAME = "hardened-chromium-service"
WRAPPER_MARKER = "# Hardened Chromium service wrapper; generated by installer."
INSTALLER_ID = "hardened-chromium-service-installer-v1"
SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_SOURCE_ROOT = SCRIPT_DIR.parent.parent


def default_prefix() -> Path:
  return Path(os.environ.get(
      "HARDENED_CHROMIUM_INSTALL_PREFIX", str(Path.home() / ".local")))


def default_config_file() -> Path:
  config_home = Path(os.environ.get(
      "XDG_CONFIG_HOME", str(Path.home() / ".config")))
  return config_home / "hardened-chromium" / "service-install.json"


def parse_args() -> argparse.Namespace:
  parser = argparse.ArgumentParser(description=__doc__)
  parser.add_argument("--source-root", type=Path, default=DEFAULT_SOURCE_ROOT,
                      help="Hardened Chromium source/build root to expose.")
  parser.add_argument("--prefix", type=Path, default=default_prefix(),
                      help="User-local prefix; defaults to ~/.local.")
  parser.add_argument("--config-file", type=Path, default=default_config_file(),
                      help="Installation metadata path.")
  parser.add_argument("--uninstall", action="store_true",
                      help="Remove only this generated wrapper and metadata.")
  parser.add_argument("--dry-run", action="store_true",
                      help="Validate and report actions without writing files.")
  parser.add_argument("--json", action="store_true",
                      help="Print machine-readable output.")
  return parser.parse_args()


def wrapper_path(prefix: Path) -> Path:
  return prefix.expanduser().resolve() / "bin" / COMMAND_NAME


def validate_source_root(source_root: Path) -> dict[str, Path]:
  source_root = source_root.expanduser().resolve()
  tools = source_root / "tools" / "hardened_chromium"
  required = {
      "service": tools / "hardened_scrape_service.py",
      "broker": tools / "hardened_scrape_broker.py",
      "launcher": tools / "run_for_automation.sh",
      "chromium": Path(os.environ.get(
          "HARDENED_CHROMIUM_BINARY", str(source_root / "out/Hardened/chrome"))),
  }
  missing = [name for name, path in required.items() if not path.exists()]
  non_executable = [name for name in ("launcher", "chromium")
                    if name not in missing and not os.access(required[name], os.X_OK)]
  if missing or non_executable:
    details = []
    if missing:
      details.append("missing " + ", ".join(missing))
    if non_executable:
      details.append("not executable " + ", ".join(non_executable))
    raise ValueError("invalid Hardened Chromium source root: " + "; ".join(details))
  return required


def wrapper_contents(service_script: Path) -> str:
  return f'''#!/usr/bin/env python3
{WRAPPER_MARKER}
from pathlib import Path
import json
import os
import sys

SERVICE_SCRIPT = Path({str(service_script)!r})

if not SERVICE_SCRIPT.is_file():
  message = "installed Hardened Chromium service target is missing: " + str(SERVICE_SCRIPT)
  if "--json" in sys.argv[1:]:
    print(json.dumps({{"ok": False, "code": "installation_target_missing", "error": message}}))
  else:
    print(message, file=sys.stderr)
  raise SystemExit(1)

os.environ["HARDENED_CHROMIUM_SERVICE_COMMAND"] = str(Path(__file__).resolve())
os.execv(sys.executable, [sys.executable, str(SERVICE_SCRIPT), *sys.argv[1:]])
'''


def write_text(path: Path, text: str, mode: int) -> None:
  path.parent.mkdir(parents=True, exist_ok=True)
  temporary = path.with_name(f".{path.name}.tmp-{os.getpid()}")
  temporary.write_text(text, encoding="utf-8")
  temporary.chmod(mode)
  temporary.replace(path)


def installation_document(
    source_root: Path,
    paths: dict[str, Path],
    command: Path,
    config_file: Path,
) -> dict[str, Any]:
  return {
      "installer": INSTALLER_ID,
      "command": str(command),
      "sourceRoot": str(source_root),
      "serviceScript": str(paths["service"]),
      "brokerScript": str(paths["broker"]),
      "launcher": str(paths["launcher"]),
      "chromiumBinary": str(paths["chromium"]),
      "configFile": str(config_file),
  }


def uninstall(command: Path, config_file: Path, dry_run: bool) -> dict[str, Any]:
  removed: list[str] = []
  retained: list[str] = []
  if command.exists():
    try:
      is_ours = WRAPPER_MARKER in command.read_text(encoding="utf-8")
    except OSError:
      is_ours = False
    if is_ours:
      if not dry_run:
        command.unlink()
      removed.append(str(command))
    else:
      retained.append(str(command))
  if config_file.exists():
    try:
      metadata = json.loads(config_file.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
      metadata = {}
    if metadata.get("installer") == INSTALLER_ID:
      if not dry_run:
        config_file.unlink()
      removed.append(str(config_file))
    else:
      retained.append(str(config_file))
  return {"ok": not retained, "uninstalled": removed, "retained": retained,
          "dryRun": dry_run}


def install(args: argparse.Namespace) -> dict[str, Any]:
  source_root = args.source_root.expanduser().resolve()
  paths = validate_source_root(source_root)
  command = wrapper_path(args.prefix)
  config_file = args.config_file.expanduser().resolve()
  document = installation_document(source_root, paths, command, config_file)
  document["ok"] = True
  document["dryRun"] = bool(args.dry_run)
  if command.exists():
    try:
      generated = WRAPPER_MARKER in command.read_text(encoding="utf-8")
    except OSError:
      generated = False
    if not generated:
      raise ValueError(
          f"refusing to overwrite non-installer command: {command}")
  if config_file.exists():
    try:
      existing = json.loads(config_file.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
      existing = {}
    if existing.get("installer") != INSTALLER_ID:
      raise ValueError(
          f"refusing to overwrite non-installer metadata: {config_file}")
  if args.dry_run:
    return document
  write_text(command, wrapper_contents(paths["service"]), 0o755)
  config_file.parent.mkdir(parents=True, exist_ok=True)
  with os.fdopen(os.open(
      config_file, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600),
      "w", encoding="utf-8") as file:
    json.dump(document, file, indent=2)
    file.write("\n")
  config_file.chmod(0o600)
  return document


def print_result(result: dict[str, Any], json_output: bool) -> None:
  if json_output:
    print(json.dumps(result, indent=2))
    return
  if result.get("uninstalled") is not None:
    print("Removed:" if result["uninstalled"] else "Nothing to remove:")
    for path in result["uninstalled"]:
      print(f"  {path}")
    for path in result.get("retained", []):
      print(f"Retained non-installer file: {path}")
    return
  print(f"Installed {COMMAND_NAME}: {result['command']}")
  print(f"Source/build: {result['sourceRoot']}")
  print("Verify: hardened-chromium-service capabilities --json")


def main() -> int:
  args = parse_args()
  command = wrapper_path(args.prefix)
  config_file = args.config_file.expanduser().resolve()
  try:
    result = (uninstall(command, config_file, args.dry_run)
              if args.uninstall else install(args))
  except (OSError, ValueError) as error:
    result = {"ok": False, "error": str(error)}
  print_result(result, args.json)
  return 0 if result.get("ok") else 1


if __name__ == "__main__":
  raise SystemExit(main())
